version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - todo-network

  app:
    image: danamostafa/todo-node:latest
    container_name: todo-app
    ports:
      - "4000:4000"
    environment:
      - mongoDbUrl=mongodb://mongo:27017/todo-db
      - PORT=4000
    depends_on:
      - mongo
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - todo-network

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_USERNAME=${DOCKER_USERNAME}
      - WATCHTOWER_PASSWORD=${DOCKER_PASSWORD}
    command: --cleanup --label-enable --interval 30
    restart: always
    networks:
      - todo-network

volumes:
  mongo-data:

networks:
  todo-network:
    driver: bridge
