# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: argocd-cm
#   namespace: argocd
# data:
#   application.instanceLabelKey: "argocd.argoproj.io/instance"
#   repositories: |
#     - url: https://github.com/DanaMostafa48/k8s.git
#       name: k8s
#       type: git